name: Backstage Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: "Repository Name"
        required: true
        type: string
      branchName:
        description: "Branch Name"
        required: true
        type: string
      nodeType:
        description: "Node Type"
        required: true
        type: string
      uploadedFile:
        description: "Path to the uploaded file"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branchName }}

      - name: Print Variables
        run: |
          echo "Repo Name: ${{ github.event.inputs.repoName }}"
          echo "Branch Name: ${{ github.event.inputs.branchName }}"
          echo "Node Type: ${{ github.event.inputs.nodeType }}"

      - name: Decode uploaded file
        run: |
          echo "${{ github.event.inputs.uploadedFile }}" | base64 --decode > uploaded_file.txt
          cat uploaded_file.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg REPO_NAME=${{ github.event.inputs.repoName }} \
            --build-arg BRANCH_NAME=${{ github.event.inputs.branchName }} \
            --build-arg NODE_TYPE=${{ github.event.inputs.nodeType }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.repoName }}:${{ github.event.inputs.branchName }} .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.inputs.repoName }}:${{ github.event.inputs.branchName }}
